baseURL = "https://www.principaleconomics.com/"
languageCode = "en-us"
title = "Principal Economics"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "economic consultant; Auckland; New zealand; economic impact analysis; cost benefit analysis; centre assessment; data analysis; decision making; econometrics"
    meta_og_title = "Principal Economics"
    meta_og_type = "website"
    meta_og_url = "http://www.principaleconomics.com"
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
    identifier = "services"
	name = "Services"
	url = "/services/"
    weight = 1

    [[menu.main]]
        identifier = "services1"
        name = "Services"
        url = "/services/cost-benefit-analysis"
        parent = "services"
        weight = 1

[[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/Work/"
    weight = 2

[[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
