baseURL = "https://awesome-ride-9abd8e.netlify.app/"
languageCode = "en-us"
title = "Principal Economics"
theme = "hugo-hero-theme"


[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "economic consultant; investment; Auckland; Wellington; New zealand; economic impact analysis; cost benefit analysis; centre assessment; data analysis; decision making; econometrics; CGE; General Equilibrium"
    meta_og_title = "Principal Economics"
    meta_og_type = "website"
    meta_og_url = "https://www.principaleconomics.com; https://www.principaleconomics.co.nz"
    meta_og_image = "https://www.principaleconomics.com/images/logo.svg"
    meta_og_description = ""
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Services"
	url = "/services/"
    	weight = 1

[[menu.main]]
    name = "Sectors"
    url = "/Sectors/"
    weight = 2

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3

[[menu.main]]
    name = "Our people"
    url = "/team/"
    weight = 5

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
